# ===============================
# = CSV FILE LOCATION
# ===============================
flight:
  data:
    file: src/main/resources/data/flights.csv


# ===============================
# = LOGGING
# ===============================
logging:
  level:
    net:
      lelyak: DEBUG

server:
  port: 8081
